# Generated by Django 5.0 on 2023-12-08 01:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Gender')),
                ('major', models.CharField(choices=[('general_practitioner', 'General Practitioner'), ('internal_medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('obstetrics_and_gynecology', 'Obstetrics and Gynecology'), ('pediatrics', 'Pediatrics'), ('oral_and_maxillofacial_surgery', 'Oral and Maxillofacial Surgery'), ('others', 'Others')], max_length=50, verbose_name='Major')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Gender')),
                ('note', models.TextField(max_length=255, verbose_name='Description')),
                ('ethnicity', models.CharField(max_length=100, verbose_name='Ethnicity')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, verbose_name='Blood_type')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=255, verbose_name='Description')),
                ('service_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Price')),
                ('date_appointment', models.DateField()),
                ('date_checkup', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('unit_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price per unit')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.appointment')),
            ],
        ),
    ]
